/// Identifier types for the NovaApp messaging engine (FASE 1 §4).
///
/// The engine keeps FOUR identity concepts strictly separate. Mixing them
/// is the classic source of authorization bugs, so each one is its own
/// type and the compiler refuses to swap them:
///
///   NovaId          NVA-7K4X-92PM  public, human-readable handle
///   AccountId       UUID           the account (routing + authorization)
///   DeviceId        UUID           one cryptographic identity per device
///   ConversationId  UUID           opaque, NEVER derived from participants
///   MessageId       UUID v4        client-generated idempotency key
///
/// Rule from §4: a Nova ID is NEVER a primary key and NEVER an
/// authorization subject. The server authorizes on AccountId against
/// conversation membership.
library;

import 'package:uuid/uuid.dart';

const Uuid _uuid = Uuid();

/// Public, user-facing handle (`NVA-XXXX-XXXX`). Display and discovery
/// only — never an authorization subject.
extension type const NovaId(String value) {
  static NovaId? tryParse(String? raw) {
    if (raw == null || raw.trim().isEmpty) return null;
    return NovaId(raw.trim());
  }

  bool get isValid => value.trim().isNotEmpty;

  @override
  String toString() => value;
}

/// Account identity. This is the subject of every authorization decision.
extension type const AccountId(String value) {
  static AccountId? tryParse(String? raw) {
    if (raw == null || raw.trim().isEmpty) return null;
    return AccountId(raw.trim());
  }

  bool get isValid => value.trim().isNotEmpty;

  @override
  String toString() => value;
}

/// Device identity. Each device holds its OWN Ed25519 identity key and
/// its OWN Double Ratchet sessions. Private keys are never shared between
/// devices (§15).
extension type const DeviceId(String value) {
  static DeviceId? tryParse(String? raw) {
    if (raw == null || raw.trim().isEmpty) return null;
    return DeviceId(raw.trim());
  }

  bool get isValid => value.trim().isNotEmpty;

  @override
  String toString() => value;
}

/// Conversation identity.
///
/// Deliberately a RANDOM UUID and never a function of the participants.
/// A derived id (e.g. `hash(accountA|accountB)`) would let anyone probe
/// whether two specific accounts talk to each other, leaking the social
/// graph. An opaque id leaks nothing.
extension type const ConversationId(String value) {
  factory ConversationId.generate() => ConversationId(_uuid.v4());

  static ConversationId? tryParse(String? raw) {
    if (raw == null || raw.trim().isEmpty) return null;
    return ConversationId(raw.trim());
  }

  bool get isValid => value.trim().isNotEmpty;

  @override
  String toString() => value;
}

/// Message identity — the idempotency key.
///
/// Generated by the CLIENT before the first send attempt and kept stable
/// across every retry, so the server deduplicates a retransmission
/// instead of creating a second message (§12, FASE 0.5 dedup).
extension type const MessageId(String value) {
  factory MessageId.generate() => MessageId(_uuid.v4());

  static MessageId? tryParse(String? raw) {
    if (raw == null || raw.trim().isEmpty) return null;
    return MessageId(raw.trim());
  }

  bool get isValid => value.trim().isNotEmpty;

  @override
  String toString() => value;
}
